runtime: java17
instance_class: F1
automatic_scaling:
  min_instances: 0
  max_instances: 1
  target_cpu_utilization: 0.5
handlers:
  - url: /.*
    script: this field is required, but ignored
env_variables:
  SPRING_PROFILES_ACTIVE: 'prod'
  DATASOURCE_URL: jdbc:postgresql:///todo_app?cloudSqlInstance=todo-434700:us-central1:spring-todo-deployment
  DB_NAME: ${sm://DB_NAME}
  DB_PASSWORD: ${sm://DB_PASSWORD}
  DB_USER: ${sm://DB_USER}
  JWT_EXPIRY: '86400000'
  JWT_SECRET_KEY: ${sm://JWT_SECRET_KEY}
