runtime: java17
instance_class: F1
automatic_scaling:
  min_instances: 0
  max_instances: 1
  target_cpu_utilization: 0.5
handlers:
  - url: /.*
    script: this field is required, but ignored
env_variables:
  DATASOURCE_URL: ${sm://DATASOURCE_URL}
  DB_NAME: ${sm://DB_NAME}
  DB_PASSWORD: ${sm://DB_PASSWORD}
  DB_USER: ${sm://DB_USER}
  JWT_EXPIRY: ${sm://JWT_EXPIRY}
  JWT_SECRET_KEY: ${sm://JWT_SECRET_KEY}
