spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/employees_project}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}
  application:
    name: "todo-app"
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration-time: ${JWT_EXPIRY:3600000}
