name: Deploy to App Engine

on:
  push:
    branches:
      - main # Deploy only when pushing to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        working-directory: ./backend # Navigate to the backend directory
        run: mvn clean package -DskipTests

      - name: Deploy to App Engine
        working-directory: ./backend # Ensure deployment happens from the backend folder
        run: |
          gcloud app deploy --quiet --project ${{ secrets.GCP_PROJECT_ID }}
